imports:
    - { resource: image_variations.yml }
    - { resource: views.yml }

parameters:
    mailer_transport:  sendmail
    mailer_host:       mailtrap.io
    mailer_user:       53236674ca83117ed
    mailer_password:   3976d6e7a03453
    mailer_port:       2525
    
    blog.posts_limit: 10    
    # e-mail address used for form submission
    app.contact_form.sender_email: no-reply@al-mustafa.de
    # e-mail address used as a message recipient
    app.contact_form.recipient_email: mahdi313esf@yahoo.com 
    app.contact_form.recipient_email_cc: amirkoklan@gmail.com
    
    app.applications.location_id: 121
twig:
    form:
        resources: ['bootstrap_3_layout.html.twig']
        #resources: ['bootstrap_3_horizontal_layout.html.twig']