ezpublish:
    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: %search_engine%
                connection: default
    siteaccess:
        list: [de, en]
        groups:
            de_group: [de]
            en_group: [en]
        default_siteaccess: de
        match:
            URIElement: 1
    system:
        de_group:
            cache_pool_name: '%cache_pool%'
            var_dir: var/site
            languages: [ger-DE]
        en_group:
            cache_pool_name: '%cache_pool%'
            var_dir: var/site
            languages: [eng-GB]