ezpublish:
    system:
        default:
            image_variations:
                teaser:
                    reference: ~
                    filters:
                        - { name: geometry/scaleexact, params: [1170,300] }
                homepage_bottom:
                    reference: ~
                    filters:
                        - { name: geometry/scaledownonly, params: [555,400] }
                homepage_thumbnail:
                    reference: ~
                    filters:
                        - { name: geometry/scaledownonly, params: [150,400] }
                blog_thumbnail:
                    reference: ~
                    filters:
                        - { name: geometry/scaledownonly, params: [250,400] }