ezpublish:
    system:
        default:
            pagelayout: AppBundle::pagelayout.html.twig
                
            content_view:
                full:
                    home:
                        controller: app_bundle.controller.home:indexAction
                        template: AppBundle:full:home.html.twig
                        match:
                            Identifier\ContentType: home
                    blog:
                        controller: app_bundle.controller.blog:showBlogPostsAction
                        template: AppBundle:full:blog.html.twig
                        match:
                            Identifier\ContentType: blog
                    blog_post:
                        template: AppBundle:full:blog_post.html.twig
                        match:
                            Identifier\ContentType: blog_post
                    event:
                        controller: app_bundle.controller.event:viewLocationAction
                        template: AppBundle:full:event.html.twig
                        match:
                            Identifier\ContentType: event
                line:
                    blog_post:
                        template: AppBundle:line:blog_post.html.twig
                        match:
                            Identifier\ContentType: blog_post