ezpublish:
    system:
        default:
            pagelayout: AppBundle::pagelayout.html.twig
                
            content_view:
                full:
                    home:
                        controller: app_bundle.controller.home:indexAction
                        template: AppBundle:full:home.html.twig
                        match:
                            Identifier\ContentType: home
                    blog:
                        controller: ez_query:LocationQueryAction
                        params:
                            query:
                                query_type: AppBundle:Children
                                parameters:
                                    parent_location_id: '%blog.location_id%'
                                    limit: '%blog.posts_limit%'
                                    sorting_content_type: blog_post
                                    sorting_field: publication_date
                                    sorting_order: desc
                                assign_results_to: posts
                        template: AppBundle:full:blog.html.twig
                        match:
                            Identifier\ContentType: blog
                    blog_post:
                        template: AppBundle:full:blog_post.html.twig
                        match:
                            Identifier\ContentType: blog_post
                line:
                    blog_post:
                        template: AppBundle:line:blog_post.html.twig
                        match:
                            Identifier\ContentType: blog_post