services:
    app_bundle.controller.application:
        class: AppBundle\Controller\ApplicationController
        arguments:
            - "@ezpublish.api.repository"
    app_bundle.controller.home:
        class: AppBundle\Controller\HomeController
        arguments:
            - "@ezpublish.api.repository"
    app_bundle.controller.event:
        class: AppBundle\Controller\EventController
        arguments:
            - "@ezpublish.api.repository"
            - "@service_container"
    appbundle.controller.blog:
        class: AppBundle\Controller\BlogController
        arguments:
            - '@ezpublish.api.repository'
    app_bundle.query_type.children:
        class: AppBundle\QueryType\ChildrenQueryType
        tags:
            - name: ezpublish.query_type